In [ ]:
import tensorflow as tf
tf.__version__

'2.7.0'

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrixDType = tf.constant([[10.,7.],
                           [7., 10.]], dtype=tf.float16)
matrixDType

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float16)>

In [ ]:
matrixDType.ndim

2

In [ ]:
tensor = tf.constant([[[2,3],[4,5]],[[10,7],[5,6]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 2,  3],
        [ 4,  5]],

       [[10,  7],
        [ 5,  6]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
tensorVar = tf.Variable([10, 7])
tensorVar

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
tensorVar[0].assign(12)
tensorVar

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12,  7], dtype=int32)>

In [ ]:
random_1 = tf.random.Generator.from_seed(24)
random_1 = random_1.normal(shape=(3,2,1))
random_1

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[ 0.10944034],
        [-0.8035768 ]],

       [[-1.7166729 ],
        [ 0.3738578 ]],

       [[-0.14371012],
        [-0.34646833]]], dtype=float32)>

In [ ]:
randomTensor = tf.random.uniform((3,2,1))
randomTensor

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[0.24359381],
        [0.4265381 ]],

       [[0.5854635 ],
        [0.11244273]],

       [[0.6848321 ],
        [0.06021082]]], dtype=float32)>

In [ ]:
not_shuffled = tf.constant([[4, 8],
                            [7, 10],
                            [5,2]])

not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  8],
       [ 7, 10],
       [ 5,  2]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  8],
       [ 7, 10],
       [ 5,  2]], dtype=int32)>

📝 Read about "Global Random Seed" and "Operational Random Seed" 

### Other ways to make tensor

In [ ]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

We can turn Numpy array => Python List

> The main difference between NumPy array and Tensorflow tensors is that tensors can be run on GPU (much faster for numerical computing).

In [ ]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from Tensors

* Shape
* Rank
* Axis or Dimension
* Size

In [ ]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0][0][0][0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

Attributes of tensor in nice way

In [ ]:
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of Dimensions: ", rank_4_tensor.ndim)
print("Shape: ", rank_4_tensor.shape)
print("Elements along 0th axis: ", rank_4_tensor.shape[0])
print("Elements along last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of Dimensions:  4
Shape:  (2, 3, 4, 5)
Elements along 0th axis:  2
Elements along last axis:  5
Total number of elements:  120


### Indexing tensors
> "... just like Python List." - Daniel Bourke (xD)


In [ ]:
# Get the first 2 elements of each dimensions 
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimensions from each index except for the final one
rank_4_tensor